---
apiVersion: v1
kind: Service
metadata:
  name: minikube-app
  labels:
    app.kubernetes.io/name: minikube-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: web-port
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: minikube-app
