---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-app2-deployment
  labels:
    app.kubernetes.io/name: minikube-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minikube-app2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minikube-app2
    spec:
      containers:
        - name: minikube-app2-container
          image: minikube-app2
          imagePullPolicy: Never
          ports:
            - name: web-port
              containerPort: 3000
