---
apiVersion: v1
kind: Service
metadata:
  name: minikube-nginx
  labels:
    app.kubernetes.io/name: minikube-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: web-port
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: minikube-nginx
